name: CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-18.04
            platform: linux
            binPath: dist
          - os: macos-latest
            platform: darwin
            binPath: dist/qml-parser.app/Contents/MacOS
    env:
      QML_PARSER_DISABLE_DOWNLOAD: 1
      QML_PARSER_BIN_PATH: ${{ matrix.binPath }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: actions/setup-node@v2

      - name: Build app
        uses: ./.github/actions/build
        with:
          with-package: false

      - run: yarn install
      - run: yarn jest
