name: Publish
on:
  push:
    tags:
      - "v*"
jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: ubuntu-18.04
            platform: linux
          - os: macos-latest
            platform: darwin

    steps:
      - name: Set RELEASE_VERSION
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Build app
        uses: ./.github/actions/build

      - uses: thedoctor0/zip-release@master
        with:
          directory: dist
          filename: ${{ matrix.platform }}.zip

      - uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          files: dist/${{ matrix.platform }}.zip
